export const enum SharedSettlementTypesEnum {
  MINING_TOWN = "MINING_TOWN",
  CASTLE_TOWN = "CASTLE_TOWN",
  FORTIFIED_SETTLEMENT = "FORTIFIED_SETTLEMENT",
  CAPITOL_SETTLEMENT = "CAPITOL_SETTLEMENT",
}